name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
      if: ${{ !contains(matrix.os, 'windows') }}
    - name: make-win
      run: make
      shell: C:\msys64\usr\bin\bash --login -c {0}
      env:
        MSYSTEM: MINGW64
        HOME: ${{github.workspace}}
      if: ${{ contains(matrix.os, 'windows') }}
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: lfs-tool
        path: lfs-tool
      
    
